### PR TITLE
Added Docker example creating a REST API, improved install instructions

### PR DESCRIPTION
**Pull request by winternet-studio**

### CODE REVIEW

**Review by ivanceras — COMMENTED** [review]
I'm sorry, I don;t want to use php in this project.

**Comment by winternet-studio** [comment]
What weird attitude is that?? Why is it a problem using PHP? It's just two simple lines of code and the user doesn't have to worry a thing about PHP!! But if you can do it just as easily in Rust why don't you just rewrite it then?!

**Comment by ivanceras** [comment]
So, I just made [svgbob_server](https://github.com/ivanceras/svgbob/tree/master/packages/svgbob_server) to be used in a REST api without using needless dependencies.

I closed this PR because I don't see it as a good engineering practice.
You essentially used apache2 server to receive the request and pass them into PHP module.
The PHP module extracts the input ascii diagram and save them into a hardcoded physically file which will be overwritten by a subsequent request while the previous request is still reading them.
Finally you invoke a CLI from PHP to execute svgbob cli and finally the result is sent to the client.

Why not just use svgbob as a library and use server library such as axium, warp, hyper to extract the request body and process the input ascii diagram right there and sent back to the client in one small self contain executable.

No need for apache2, php module, and physical files.

**Comment by winternet-studio** [comment]
Ok, that's even better! I just didn't know how to do that :) I did what I knew - which was working just fine in normal conditions. But thanks for the more optimal solution!

**Pull request closed without merging**
