### PR TITLE
New flag to handle inline string parsing

### LINKED ISSUE #15: Command line stdin conversion
I would like to make a [pandoc filter](https://github.com/jgm/pandocfilters) that does basically what spongedown does with ascii drawings. But I can't find how to properly pass a multiline string to `svgbob` through the command line.
How is this done ?

On Windows, I have tried things like : 
`echo "+--+\n|  |\n+--+" | svgbob`
but the `\n` are kept as they are, and trying to pass the raw string from python actually ends the command in the middle of the string, effectively yielding an echo of the first line of the drawing.

### PR DESCRIPTION
**Pull request by yhql**
Should fix [issue 15](https://github.com/ivanceras/svgbobrus/issues/15) (tested on Windows and linux)

### CODE REVIEW

**Comment by ivanceras** [comment]
I think this is OK

**Comment by ivanceras** [comment]
This needs more refinement.
You can not just do 
```
echo "+--+\n| |\n+--+" | svgbob -s
```

**Comment by yhql** [comment]
It should still work just like before if you remove the -s flag. I made the modification so that you can still do :
`echo "+--+\n| |\n+--+" | svgbob`
and for the cases where you don't want to use `echo` : 
`svgbob -s "+--+\n| |\n+--+"`

**Comment by ivanceras** [comment]
Ah ok, got it.
However there is an inconsistency though.
This works fine.
`svgbob -s "+--+\n| |\n+--+"`

but not

`svgbob -s "hello"`

neither
`svgbob -s "----------+-----------"`

This works though
`svgbob -s "||||||"`

I'm guessing there is a conflict with subcommands with the clap library.

**Comment by yhql** [comment]
Ah yes it seems clap is parsing the command in an unexpected way, but as it suggests in some case, you can do this : 
`svgbob -s -- "hello"` 
which works fine for me

**Comment by ivanceras** [comment]
Ok, I've changed the Readme and I will release a new svgbob_cli into crates.io shortly.

**Pull request merged**
